### PR TITLE
64-bit MultiClamp and Windows header files

### PR DESCRIPTION
**Pull request by meganbkratz**
This PR allows us to use the new MulticlampCommander version 2.2.0.x, which runs on 64-bit windows and can interact with 64-bit python processes. 

Major changes:
- CParser.winDefs now checks system architecture and parses Windows header files as 32- or 64- bit as appropriate. Caches for both 32- and 64-bit parsings have been added.
- The AxMultiClampMsg.dll and associated Multiclamp header files have been removed from the repository. Instead CLibrary.find_lib is used to find the .dll file on the machine, and header files have been cached. The cached header files are those that come with MC Commander 2.2.0.2 and seem to be backwards compatible.

Minor changes:
- added debugging statements to multiclamp.py and MultiClampTelegraph.py

Testing:
This branch has been lightly tested (acq4 opens, loads the clamp device successfully, opens a Clamp module, and runs a few traces in bath mode) on these systems:

- Rig4 - 64-bit Windows7, MultiClamp700B, Commander version 2.2.0.2 and 2.2.0.1, 64-bit python
- Rig4 - 64-bit Windows 7, MultiClamp700B, Commander version 2.1.0.16, 64-bit python with a 32-bit python process to connect to the commander
- Rig2 - 32-bit Windows7, MultiClamp700B, Commander version 2.1.0.16, 32-bit python
- Rig3 - 32-bit Windows7, MultiClamp700A, Commander version 1.3.0.05, 32-bit python

### CODE REVIEW

**Comment by campagnola** [comment]
This looks fantastic! I'll test it on our rigs and then merge.

Minor note: `logging.debug()` is the Python-way of having conditional debugging messages.

Side note: the 64-bit MCC has some bugs for which the developers have a fixed version that should be released in a month or so (or you can ask them for the version they have now). Specifically, some settings like the LPF cutoff are not set correctly from the API, so beware..

**Comment by campagnola** [comment]
Suggested changes in https://github.com/meganbkratz/acq4/pull/1

**Comment by meganbkratz** [comment]
Hey Luke, I incorporated the changes you suggested, and they all work fine on my end.

**Comment by campagnola** [comment]
Looks good to me. Thank you thank you, this is awesome!

**Pull request merged**
